# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos_smart_rollup_mock"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
tezos_crypto_rs = { version = "0.4", default-features = false }
tezos_data_encoding = "0.4"

[dependencies.tezos_smart_rollup_encoding]
path = "../tezos_smart_rollup_encoding"
default-features = false

[dependencies.tezos_smart_rollup_core]
path = "../tezos_smart_rollup_core"
default-features = false

[dependencies.tezos_smart_rollup_host]
path = "../tezos_smart_rollup_host"
default-features = false

[dev-dependencies.tezos_smart_rollup_host]
path = "../tezos_smart_rollup_host"
features = ["default"]