---

# General setup

# Basic configuration to guard against double-pipelines
workflow:
  rules:
    # The following guard is the standard way to run pipelines for branches. It
    # runs a CI pipeline each time the branch is pushed to (including
    # force-push, push of fixup commits, rebase, etc.).
    # Future additions might include rules for MR events and for regular
    # schedules.
    # See https://docs.gitlab.com/ee/ci/yaml/README.html#workflow for additional
    # details.
    - if: '$CI_PIPELINE_SOURCE == "push"'

variables:
  ## This value MUST be the same as `opam_repository_tag` in `scripts/version.sh`
  build_deps_image_version: 161654c289ab0c39c425e9b4cc8d7b7558d1d462
  build_deps_image_name: registry.gitlab.com/tezos/opam-repository
  public_docker_image_name: docker.io/${CI_PROJECT_PATH}-
  GIT_STRATEGY: fetch
  GIT_DEPTH: "1"
  GET_SOURCES_ATTEMPTS: "2"
  ARTIFACT_DOWNLOAD_ATTEMPTS: "2"

stages:
  - build
  - test
  - doc
  - test-doc-scripts
  - packaging
  - build_release
  - publish_release
  - test_coverage
  - publish_coverage

# Basic, specialised, minimal, orthogonal templates

# Image templates
.image_template__runtime_build_test_dependencies_template:
  image: ${build_deps_image_name}:runtime-build-test-dependencies--${build_deps_image_version}

.image_template__runtime_build_dependencies_template:
  image: ${build_deps_image_name}:runtime-build-dependencies--${build_deps_image_version}

.image_template__latest:
  image: docker:latest

# Rules template

# Rules for all the jobs that need to be run on development branches (typically
# those that have an MR, but also some experiments, etc.)
.rules_template__development:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /-release$/ && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_TAG != null && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - when: on_success

# Rules for all the jobs that can be manually run on development branches
.rules_template__development_manual:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /-release$/ && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_TAG != null && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - when: manual

# Rules for all the jobs that are run only for the master branch and the like
# (tags, releases, etc.)
.rules_template__master_and_releases:
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "tezos"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /-release$/ && $CI_PROJECT_NAMESPACE == "tezos"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAMESPACE == "tezos"'
      when: on_success
    - when: never

# Rules for all the jobs that are run only for the master branch
.rules_template__master:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_NAMESPACE == "tezos"'
      when: on_success
    - when: never

# Rules for specific topics: doc, opam, etc.
.rules_template__development_documentation:
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /-release$/ && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /doc/'
      when: always
    - changes:
        - /docs
      when: always
    - when: manual
.rules_template__development_opam:
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_BRANCH =~ /-release$/ && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /opam/'
      when: always
    - changes:
        - /**/*.opam
        - /**/dune
        - /**/dune.inc
        - /**/*.dune.inc
        - /scripts/version.sh
        - /.gitlab-ci.yml
      when: always
    - when: never


# Actual jobs are defined in these included files

include:
  - .gitlab/ci/build.yml
  - .gitlab/ci/lints.yml
  - .gitlab/ci/unittest.yml
  - .gitlab/ci/integration.yml
  - .gitlab/ci/liquidity-baking-scripts-integrity.yml
  - .gitlab/ci/coq.yml
  - .gitlab/ci/tezt.yml
  - .gitlab/ci/doc.yml
  - .gitlab/ci/opam.yml
  - .gitlab/ci/publish.yml
  - .gitlab/ci/coverage.yml
  - .gitlab/ci/test-doc-scripts.yml
