variables:
  ## Please update `scripts/version.sh` accordingly
  build_deps_image_version: 300201d4607ea6d1648c77653300676bf0ae16ed
  build_deps_image_name: registry.gitlab.com/tezos/opam-repository
  public_docker_image_name: docker.io/${CI_PROJECT_PATH}
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1
  GET_SOURCES_ATTEMPTS: 2
  ARTIFACT_DOWNLOAD_ATTEMPTS: 2

stages:
  - doc
  - build
  - test
  - packaging
  - publish

############################################################
## Stage: build (only MR)                                 ##
############################################################

.build_template: &build_definition
  image: ${build_deps_image_name}:${build_deps_image_version}
  stage: build
  except:
    - master
    - alphanet
    - zeronet
    - mainnet
    - alphanet-staging
    - zeronet-staging
    - mainnet-staging
    - zeronet-snapshots
    - mainnet-snapshots

build:
  <<: *build_definition
  script:
    - . ./scripts/version.sh
    - dune build @runtest_dune_template
    - make all build-test
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - _build
    expire_in: 1 day
  tags:
    - gitlab-org

############################################################
## Stage: test                                           ##
############################################################

# depends on the build stage. download the _build artifacts
# and run make to recreate all symlinks
.test_template: &test_definition
  <<: *build_definition
  dependencies:
    - build
  before_script:
    - . ./scripts/version.sh
    - make
  tags:
    - gitlab-org
  retry: 2

check_opam_deps:
  <<: *test_definition
  script:
    - if [ "${build_deps_image_version}" != "${opam_repository_tag}" ] ; then
        echo "Inconsistent dependencies hash between 'scripts/version.sh' and '.gitlab-ci.yml'." ;
        echo "${build_deps_image_version} != ${opam_repository_tag}" ;
        exit 1 ;
      fi
    - ./scripts/opam-check.sh
    - ./scripts/check_opam_test.sh
  stage: test

check_opam_lint:
  <<: *test_definition
  script:
    - find . ! -path "./_opam/*" -name "*.opam" -exec opam lint {} +;
  stage: test

check_indentation:
  <<: *test_definition
  script:
    - dune build @runtest_indent
  stage: test

check_python_lint:
  <<: *test_definition
  script:
    - make -C tests_python lint_all
    - make -C tests_python typecheck
  stage: test

############################################################
## Stage: test (only MR)                                  ##
############################################################

.test_template: &test_definition
  <<: *build_definition
  stage: test
  before_script:
    - sudo apk add py-pip python3 python3-dev
    - sudo pip install --upgrade pip
    - sudo pip3 install -r tests_python/requirements.txt
    - make all
  dependencies:
    - build

unit:stdlib:
  <<: *test_definition
  script:
    - dune build @src/lib_stdlib/runtest
  stage: test

unit:stdlib_unix:
  <<: *test_definition
  script:
    - dune build @src/lib_stdlib_unix/runtest
  stage: test

unit:data_encoding:
  <<: *test_definition
  script:
    - dune build @src/lib_data_encoding/runtest
  stage: test

unit:storage:
  <<: *test_definition
  script:
    - dune build @src/lib_storage/runtest
  stage: test

unit:crypto:
  <<: *test_definition
  script:
    - dune build @src/lib_crypto/runtest
  stage: test

unit:shell:
  <<: *test_definition
  script:
    - dune build @src/lib_shell/runtest
  stage: test

unit:p2p:io-scheduler:
  <<: *test_definition
  script:
    - dune build @src/lib_p2p/runtest_p2p_io_scheduler_ipv4
  stage: test

unit:p2p:socket:
  <<: *test_definition
  script:
    - dune build @src/lib_p2p/runtest_p2p_socket_ipv4
  stage: test

unit:p2p:pool:
  <<: *test_definition
  script:
    - dune build @src/lib_p2p/runtest_p2p_pool_ipv4
  stage: test

unit:proto_alpha:lib_protocol:
  <<: *test_definition
  script:
    - dune build @src/proto_alpha/lib_protocol/runtest
  stage: test

unit:proto_alpha:lib_client:
  <<: *test_definition
  script:
    - dune build @src/proto_alpha/lib_client/test/runtest
  stage: test

unit:p2p:peerset:
  <<: *test_definition
  script:
    - dune build @src/lib_p2p/runtest_p2p_peerset
  stage: test

unit:p2p:ipv6set:
  <<: *test_definition
  script:
    - dune build @src/lib_p2p/runtest_p2p_ipv6set
  stage: test

unit:p2p:banned_peers:
  <<: *test_definition
  script:
    - dune build @src/lib_p2p/runtest_p2p_banned_peers
  stage: test

unit:client_alpha:vote:
  <<: *test_definition
  script:
    - dune build @src/proto_alpha/lib_delegate/runtest_vote
  stage: test

unit:validation:
  <<: *test_definition
  script:
    - dune build @src/lib_validation/runtest
  stage: test

unit:micheline:
  <<: *test_definition
  script:
    - dune build @src/lib_micheline/runtest
  stage: test

############################################################
## Stage: run shell integration tests                     ##
############################################################

integration:basic.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_basic.sh
  stage: test

integration:contracts.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_contracts.sh
  stage: test

integration:contracts_opcode.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_contracts_opcode.sh
  stage: test

integration:contracts_macros.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_contracts_macros.sh
  stage: test

integration:contracts_mini_scenarios.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_contracts_mini_scenarios.sh
  stage: test

integration:multinode.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_multinode.sh
  stage: test

integration:inject.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_injection.sh
  stage: test

integration:voting.sh:
  <<: *test_definition
  script:
    - dune build @src/bin_client/runtest_voting.sh
  stage: test

integration:proto:sandbox:
  <<: *test_definition
  script:
    - dune build @runtest_sandbox
  stage: test

############################################################
## Stage: run OCaml integration tests                     ##
############################################################

integration:sandboxes:voting:
  <<: *test_definition
  script:
    - ROOT_PATH=$PWD/flextesa-voting-demo dune build @src/bin_flextesa/runtest_sandbox_voting_demo
  artifacts:
    paths:
    - flextesa-voting-demo
    expire_in: 1 day
    when: on_failure
  allow_failure: true # This test uses too much resources for GitLab's workers
  stage: test

integration:sandboxes:acc-baking:
  <<: *test_definition
  script:
    - ROOT_PATH=$PWD/flextesa-acc-sdb dune build @src/bin_flextesa/runtest_sandbox_accusations_simple_double_baking
  artifacts:
    paths:
    - flextesa-acc-sdb
    expire_in: 1 day
    when: on_failure
  stage: test

integration:sandboxes:acc-endorsement:
  <<: *test_definition
  script:
    - ROOT_PATH=$PWD/flextesa-acc-sde dune build @src/bin_flextesa/runtest_sandbox_accusations_simple_double_endorsing
  artifacts:
    paths:
    - flextesa-acc-sde
    expire_in: 1 day
    when: on_failure
  stage: test

############################################################
## Stage: run python integration tests                    ##
############################################################

##BEGIN_INTEGRATION_PYTHON##
integration:baker_endorser:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_baker_endorser.py
  stage: test

integration:basic:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_basic.py
  stage: test

integration:contract:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_contract.py
  stage: test

integration:contract_baker:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_contract_baker.py
  stage: test

integration:cors:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_cors.py
  stage: test

integration:injection:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_injection.py
  stage: test

integration:many_bakers:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_many_bakers.py
  stage: test

integration:many_nodes:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_many_nodes.py
  stage: test

integration:mempool:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_mempool.py
  stage: test

integration:multinode:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_multinode.py
  stage: test

integration:rpc:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_rpc.py
  stage: test

integration:tls:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_tls.py
  stage: test

integration:voting:
  <<: *test_definition
  script:
    - pytest tests_python/tests/test_voting.py
  stage: test


##END_INTEGRATION_PYTHON##

############################################################
## Stage: run doc integration tests                       ##
############################################################

documentation:
  <<: *test_definition
  stage: test
  script:
    - make doc-html

linkcheck:
  <<: *test_definition
  stage: test
  script:
    - make doc-html-and-linkcheck
  allow_failure: true

############################################################
## Stage: building opam packages (only master and *opam*) ##
############################################################

.opam_template: &opam_definition
  image: ${build_deps_image_name}:opam--${build_deps_image_version}
  stage: packaging
  dependencies: []
  only:
    - master
    - /^.*opam.*$/
  script:
    - ./scripts/opam-pin.sh
    - opam depext --yes ${package}
    - opam install --yes ${package}
    - opam reinstall --yes --with-test ${package}
  tags:
    - gitlab-org

##BEGIN_OPAM##
opam:00:ocplib-json-typed:
  <<: *opam_definition
  variables:
    package: ocplib-json-typed

opam:01:ocplib-json-typed-bson:
  <<: *opam_definition
  variables:
    package: ocplib-json-typed-bson

opam:02:tezos-stdlib:
  <<: *opam_definition
  variables:
    package: tezos-stdlib

opam:03:tezos-data-encoding:
  <<: *opam_definition
  variables:
    package: tezos-data-encoding

opam:04:ocplib-resto:
  <<: *opam_definition
  variables:
    package: ocplib-resto

opam:05:tezos-error-monad:
  <<: *opam_definition
  variables:
    package: tezos-error-monad

opam:06:ocplib-resto-directory:
  <<: *opam_definition
  variables:
    package: ocplib-resto-directory

opam:07:blake2:
  <<: *opam_definition
  variables:
    package: blake2

opam:08:hacl:
  <<: *opam_definition
  variables:
    package: hacl

opam:09:secp256k1:
  <<: *opam_definition
  variables:
    package: secp256k1

opam:10:tezos-clic:
  <<: *opam_definition
  variables:
    package: tezos-clic

opam:11:tezos-rpc:
  <<: *opam_definition
  variables:
    package: tezos-rpc

opam:12:uecc:
  <<: *opam_definition
  variables:
    package: uecc

opam:13:tezos-crypto:
  <<: *opam_definition
  variables:
    package: tezos-crypto

opam:14:tezos-event-logging:
  <<: *opam_definition
  variables:
    package: tezos-event-logging

opam:15:tezos-micheline:
  <<: *opam_definition
  variables:
    package: tezos-micheline

opam:16:lmdb:
  <<: *opam_definition
  variables:
    package: lmdb

opam:17:tezos-base:
  <<: *opam_definition
  variables:
    package: tezos-base

opam:18:pbkdf:
  <<: *opam_definition
  variables:
    package: pbkdf

opam:19:ocplib-resto-cohttp:
  <<: *opam_definition
  variables:
    package: ocplib-resto-cohttp

opam:20:irmin-lmdb:
  <<: *opam_definition
  variables:
    package: irmin-lmdb

opam:21:tezos-shell-services:
  <<: *opam_definition
  variables:
    package: tezos-shell-services

opam:22:tezos-stdlib-unix:
  <<: *opam_definition
  variables:
    package: tezos-stdlib-unix

opam:23:bip39:
  <<: *opam_definition
  variables:
    package: bip39

opam:24:tezos-rpc-http:
  <<: *opam_definition
  variables:
    package: tezos-rpc-http

opam:25:tezos-storage:
  <<: *opam_definition
  variables:
    package: tezos-storage

opam:26:ledgerwallet:
  <<: *opam_definition
  variables:
    package: ledgerwallet

opam:27:tezos-client-base:
  <<: *opam_definition
  variables:
    package: tezos-client-base

opam:28:ledgerwallet-tezos:
  <<: *opam_definition
  variables:
    package: ledgerwallet-tezos

opam:29:tezos-signer-services:
  <<: *opam_definition
  variables:
    package: tezos-signer-services

opam:30:tezos-signer-backends:
  <<: *opam_definition
  variables:
    package: tezos-signer-backends

opam:31:tezos-protocol-environment-sigs:
  <<: *opam_definition
  variables:
    package: tezos-protocol-environment-sigs

opam:32:tezos-client-commands:
  <<: *opam_definition
  variables:
    package: tezos-client-commands

opam:33:tezos-protocol-compiler:
  <<: *opam_definition
  variables:
    package: tezos-protocol-compiler

opam:34:tezos-protocol-environment:
  <<: *opam_definition
  variables:
    package: tezos-protocol-environment

opam:35:tezos-client-base-unix:
  <<: *opam_definition
  variables:
    package: tezos-client-base-unix

opam:36:tezos-protocol-alpha:
  <<: *opam_definition
  variables:
    package: tezos-protocol-alpha

opam:37:tezos-protocol-environment-shell:
  <<: *opam_definition
  variables:
    package: tezos-protocol-environment-shell

opam:38:tezos-client-alpha:
  <<: *opam_definition
  variables:
    package: tezos-client-alpha

opam:39:tezos-protocol-updater:
  <<: *opam_definition
  variables:
    package: tezos-protocol-updater

opam:40:tezos-baking-alpha:
  <<: *opam_definition
  variables:
    package: tezos-baking-alpha

opam:41:tezos-protocol-demo:
  <<: *opam_definition
  variables:
    package: tezos-protocol-demo

opam:42:tezos-protocol-genesis:
  <<: *opam_definition
  variables:
    package: tezos-protocol-genesis

opam:43:ocplib-resto-json:
  <<: *opam_definition
  variables:
    package: ocplib-resto-json

opam:44:tezos-p2p:
  <<: *opam_definition
  variables:
    package: tezos-p2p

opam:45:tezos-validation:
  <<: *opam_definition
  variables:
    package: tezos-validation

opam:46:tezos-baking-alpha-commands:
  <<: *opam_definition
  variables:
    package: tezos-baking-alpha-commands

opam:47:tezos-client-alpha-commands:
  <<: *opam_definition
  variables:
    package: tezos-client-alpha-commands

opam:48:tezos-client-demo:
  <<: *opam_definition
  variables:
    package: tezos-client-demo

opam:49:tezos-client-genesis:
  <<: *opam_definition
  variables:
    package: tezos-client-genesis

opam:50:ocplib-ezresto:
  <<: *opam_definition
  variables:
    package: ocplib-ezresto

opam:51:tezos-embedded-protocol-alpha:
  <<: *opam_definition
  variables:
    package: tezos-embedded-protocol-alpha

opam:52:tezos-shell:
  <<: *opam_definition
  variables:
    package: tezos-shell

opam:53:tezos-embedded-protocol-demo:
  <<: *opam_definition
  variables:
    package: tezos-embedded-protocol-demo

opam:54:tezos-embedded-protocol-genesis:
  <<: *opam_definition
  variables:
    package: tezos-embedded-protocol-genesis

opam:55:tezos-endorser-alpha-commands:
  <<: *opam_definition
  variables:
    package: tezos-endorser-alpha-commands

opam:56:tezos-client:
  <<: *opam_definition
  variables:
    package: tezos-client

opam:57:ocplib-ezresto-directory:
  <<: *opam_definition
  variables:
    package: ocplib-ezresto-directory

opam:58:tezos-accuser-alpha:
  <<: *opam_definition
  variables:
    package: tezos-accuser-alpha

opam:59:tezos-mempool-alpha:
  <<: *opam_definition
  variables:
    package: tezos-mempool-alpha

opam:60:tezos-protocol-alpha-tests:
  <<: *opam_definition
  variables:
    package: tezos-protocol-alpha-tests

opam:61:tezos-endorser-alpha:
  <<: *opam_definition
  variables:
    package: tezos-endorser-alpha

opam:62:tezos-accuser-alpha-commands:
  <<: *opam_definition
  variables:
    package: tezos-accuser-alpha-commands

opam:63:tezos-protocol-alpha-parameters:
  <<: *opam_definition
  variables:
    package: tezos-protocol-alpha-parameters

opam:64:tezos-baker-alpha:
  <<: *opam_definition
  variables:
    package: tezos-baker-alpha

opam:65:tezos-network-sandbox:
  <<: *opam_definition
  variables:
    package: tezos-network-sandbox

opam:66:tezos-signer:
  <<: *opam_definition
  variables:
    package: tezos-signer

opam:67:tezos-node:
  <<: *opam_definition
  variables:
    package: tezos-node

opam:68:ocplib-json-typed-browser:
  <<: *opam_definition
  variables:
    package: ocplib-json-typed-browser


##END_OPAM##



############################################################
## Stage: publish                                         ##
############################################################

publish:docker:
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  stage: publish
  only:
    - master@tezos/tezos
    - alphanet@tezos/tezos
    - zeronet@tezos/tezos
    - mainnet@tezos/tezos
    - alphanet-staging@tezos/tezos
    - zeronet-staging@tezos/tezos
    - mainnet-staging@tezos/tezos
    - zeronet-snapshots@tezos/tezos
    - mainnet-snapshots@tezos/tezos
  before_script:
    - apk add git
    - mkdir ~/.docker || true
    - echo "${CI_DOCKER_AUTH}" > ~/.docker/config.json
  script:
    - LAST_COMMIT_DATE_TIME=$(git log --pretty=format:"%cd" -1 --date="format:%Y%m%d%H%M%S" 2>&1)
    - ./scripts/create_docker_image.sh
        "${public_docker_image_name}" "${CI_COMMIT_REF_NAME}"
    - docker push "${public_docker_image_name}:${CI_COMMIT_REF_NAME}"
    - docker tag "${public_docker_image_name}:${CI_COMMIT_REF_NAME}" "${public_docker_image_name}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_${LAST_COMMIT_DATE_TIME}"
    - docker push "${public_docker_image_name}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_${LAST_COMMIT_DATE_TIME}"
  tags:
    - safe_docker

publish:doc:
  image: ${build_deps_image_name}:${build_deps_image_version}
  stage: doc
  only:
    - master@tezos/tezos
    - alphanet@tezos/tezos
    - zeronet@tezos/tezos
    - mainnet@tezos/tezos
  before_script:
    - echo "${CI_PK_GITLAB_DOC}" > ~/.ssh/id_ed25519
    - echo "${CI_KH}" > ~/.ssh/known_hosts
    - chmod 400 ~/.ssh/id_ed25519
  script:
    - make doc-html
    - git clone git@gitlab.com:${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAMESPACE}.gitlab.io gitlab.io
    - rsync --recursive --links --perms --delete --verbose
        --exclude=.doctrees
        docs/_build/ gitlab.io/public/"${CI_COMMIT_REF_NAME}"
    - cd gitlab.io
    - if [ -z "$(git status -s)" ] ; then
        echo "Nothing to commit!" ;
      else
        git add public/"${CI_COMMIT_REF_NAME}" ;
        git commit -m "Import doc for ${CI_COMMIT_REF_NAME} (${CI_COMMIT_SHA})" ;
        git push origin master ;
      fi
  tags:
    - gitlab-org
