# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
# SPDX-FileCopyrightText: 2022 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-core"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.mockall]
version = "0.11.0"
optional = true

[dev-dependencies.mockall]
version = "0.11.0"

[features]
"testing" = ["mockall"]
