# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos_smart_rollup"
version = "0.1.0"
edition = "2021"
include = ["../../README.md"]

[dependencies.tezos_smart_rollup_core]
path = "../tezos_smart_rollup_core"
default-features = false

[dependencies.tezos_smart_rollup_host]
path = "../tezos_smart_rollup_host"
default-features = false

[dependencies.tezos_smart_rollup_debug]
path = "../tezos_smart_rollup_debug"

[dependencies.tezos_smart_rollup_encoding]
path = "../tezos_smart_rollup_encoding"
default-features = false

[dependencies.tezos_smart_rollup_storage]
path = "../tezos_smart_rollup_storage"
optional = true

[dependencies.tezos_smart_rollup_entrypoint]
path = "../tezos_smart_rollup_entrypoint"
default-features = false

[dependencies.tezos_smart_rollup_mock]
path = "../tezos_smart_rollup_mock"
optional = true

[dependencies.tezos_crypto_rs]
version = "0.4"
default-features = false
optional = true

[dependencies.tezos_data_encoding]
version = "0.4"
optional = true

[features]
default = ["std", "crypto", "dlmalloc", "panic-hook", "data-encoding", "storage"]
crypto = ["tezos_crypto_rs"]
alloc = ["tezos_smart_rollup_entrypoint/alloc"]
dlmalloc = ["tezos_smart_rollup_entrypoint/dlmalloc"]
panic-hook = ["tezos_smart_rollup_entrypoint/panic-hook"]
data-encoding = ["tezos_data_encoding", "tezos_smart_rollup_encoding/default"]
storage = ["tezos_smart_rollup_storage"]
std = ["alloc", "tezos_smart_rollup_entrypoint/std"]
testing = ["crypto", "tezos_smart_rollup_mock"]