# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[workspace]

members = [
  # Kernel Dev
  "tezos_smart_rollup_core",
  "tezos_smart_rollup_host",
  # UX
  "installer_kernel",
  "installer_client"
]
