# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos_smart_rollup_debug"
version = "0.1.0"
edition = "2021"

[dependencies.tezos_smart_rollup_core]
path = "../tezos_smart_rollup_core"

[dependencies.tezos_smart_rollup_host]
path = "../tezos_smart_rollup_host"
default-features = false

[dev-dependencies.tezos_smart_rollup_core]
path = "../tezos_smart_rollup_core"
features = ["testing"]

[features]
default = ["alloc"]
alloc = []
