# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos_ethereum"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive-types = { version = "0.11.1", default-features = false }
rlp = "0.5.2"
hex = "0.4"
sha3 = { version = "0.10.6", default-features = false }
tezos_crypto_rs = { version = "0.4", default-features = false }

[dependencies.tezos-smart-rollup-encoding]
path = "../../kernel_sdk/encoding"

