# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
# SPDX-FileCopyrightText: 2023 Marigold <contact@marigold.dev>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos-smart-rollup-panic-hook"
version = "0.1.0"
edition = "2021"

[dependencies.tezos-smart-rollup-core]
path = "../core"

[features]
default = ["abort", "debug"]
abort = []
debug = []
