# SPDX-FileCopyrightText: 2023 Nomadic Labs <contact@nomadic-labs.com>
#
# SPDX-License-Identifier: MIT

[package]
name = 'evm_mockup_kernel'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ["cdylib"]

[dependencies]
kernel = { git = "https://gitlab.com/tezos/kernel", rev= "826e47a4", default-features = false }
host = { git = "https://gitlab.com/tezos/kernel", rev= "826e47a4"  }
debug = { git = "https://gitlab.com/tezos/kernel", rev= "826e47a4" }
mock_runtime = { git = "https://gitlab.com/tezos/kernel", rev= "826e47a4", default-features = false }

num-bigint = "0.3"
