# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "tezos_smart_rollup_host"
version = "0.1.0"
edition = "2021"

[dependencies.tezos_smart_rollup_core]
path = "../tezos_smart_rollup_core"

[dependencies.tezos_crypto_rs]
version = "0.4"
default-features = false
optional = true

[dependencies.thiserror]
version = "1.0"
optional = true

[dev-dependencies]
mockall = "0.11.0"

[dev-dependencies.tezos_smart_rollup_core]
path = "../tezos_smart_rollup_core"
features = ["testing"]

[features]
default = ["alloc", "crypto", "std"]
crypto = ["tezos_crypto_rs"]
alloc = ["thiserror"]
testing = ["crypto"]
# Required for 'impl Error for RuntimeError'
std = []